name: Update documentation for release

on:
  # Allow to run the workflow by dispatching
  workflow_dispatch:

jobs:

  update-documentation: 
    runs-on: ubuntu-latest

    steps:

      - name: Pull xtermjs documentation repo
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      
      - name: Pull xtermjs repo
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          repository: xtermjs/xterm.js
          path: _xterm.js

      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # v3.5.1
        with:
          node-version: '14'

      - name: Build the docs
        id: build_docs
        run: |
        
          # install deps
          npm install -g yarn && yarn install

          # build docs
          npm run build:docs

          # run vt features
          cd _xterm.js && npm install mustache && npm run --silent vtfeatures > ../_docs/api/vtfeatures.md & cd ..
      
      - name: Fetch xterm.js version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@7aa1d82604bb2dbe377a64ca35e692e6fe333c9c # v1.2.3
        with:
          path: _xterm.js
      
      - name: Create Pull Request
        uses: https://github.com/peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04 # v4.2.3
        with:
          commit-message: Update documentation to v${{ steps.package-version.outputs.current-version }}
          title: Update documentation to v${{ steps.package-version.outputs.current-version }}
          body: Update documentation to v${{ steps.package-version.outputs.current-version }}
          branch: update-docs-${{ steps.package-version.outputs.current-version }}
